# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-03-07 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axf', '0008_auto_20190307_0749'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productid', models.CharField(default='', max_length=10)),
                ('productimg', models.CharField(default='', max_length=256)),
                ('productname', models.CharField(default='', max_length=40)),
                ('productlongname', models.CharField(default='', max_length=256)),
                ('isxf', models.IntegerField(default=1)),
                ('pmdesc', models.IntegerField(default=1)),
                ('specifics', models.CharField(default='', max_length=10)),
                ('price', models.FloatField(default='')),
                ('marketprice', models.FloatField(default=1)),
                ('categoryid', models.IntegerField(default=1)),
                ('childcid', models.IntegerField(default=1)),
                ('childcidname', models.CharField(default='', max_length=40)),
                ('dealerid', models.CharField(default='', max_length=40)),
                ('storenums', models.IntegerField(default=1)),
                ('productnum', models.IntegerField(default=1)),
            ],
        ),
    ]
